List dummyOrder() {
  return [
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kemerdekaan Indonesia',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Butuh Konfirmasi',
      'type': 'Instagram Stories',
      'detail': null,
    },
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kartini',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Upload Draft',
      'type': 'Instagram Stories',
      'detail': null,
    },
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kemerdekaan Indonesia',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Menunggu Konfirmasi Bukti Tayang',
      'type': 'Instagram Stories',
      'detail': null,
    },
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kemerdekaan Indonesia',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Menunggu Konfirmasi Insight',
      'type': 'Instagram Stories',
      'detail': null,
    },
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kemerdekaan Indonesia',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Menunggu Konfirmasi Draft',
      'type': 'Instagram Stories',
      'detail': null,
    },
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kemerdekaan Indonesia',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Ditolak',
      'type': 'Instagram Stories',
      'detail': null,
    },
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kemerdekaan Indonesia',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Revisi Draft',
      'type': 'Instagram Stories',
      'detail': null,
    },
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kemerdekaan Indonesia',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Upload Bukti Tayang',
      'type': 'Instagram Stories',
      'detail': null,
    },
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kemerdekaan Indonesia',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Selesai',
      'type': 'Instagram Stories',
      'detail': null,
    },
    {
      'image': 'assets/images/img_order.png',
      'title': 'Campaign Hari Kemerdekaan Indonesia',
      'institution': 'Nestle Indonesia',
      'periode': '12 Des 2022 - 31 Des 2022',
      'status': 'Upload Insight',
      'type': 'Instagram Stories',
      'detail': null,
    },
  ];
}